### PR TITLE
Add motd

### PR DESCRIPTION
**Pull request by thomasbeaudry**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Looks great!

Why just x2go? I think we can get this to work for all x sessions?

**Comment by thomasbeaudry** [comment]
what other x session do we use here?

**Comment by gdevenyi** [comment]
The default session is the plasma one. I was hoping we could find a method which doesn't have to modify every session type though.

**Comment by gdevenyi** [comment]
I believe the solution is to move MOTD things to `/etc/Xsession.d/*` see `man Xsession` for details on what the xsession scripts are.

**Review by gdevenyi — CHANGES_REQUESTED** [review]

**Comment by gdevenyi** [comment]
Actually, lets not merge the script, but the SSH and local login config should be in the common config, and the workstation should get the additional X config.

**Comment by thomasbeaudry** [comment]
> This looks good, only question left is, does it show twice for ssh users? And perhaps, could this be merged into a single script with an early exit?

No it only shows once for ssh users (I have it running on cicws45)

**Comment by gdevenyi** [comment]
Got it, looks good. I would like the MOTD to go into common and the zenity one to stay in workstations and then we're good to merge.

**Comment by gdevenyi** [comment]
Great. Can you please do some manual steps for cicus03 as well.

**Comment by thomasbeaudry** [comment]
What manual steps do you want for cicus03??

**Comment by gdevenyi** [comment]
cicus03 isn't setup for ansible to manage it, just manually install the MOTD bits

**Pull request merged**
