### PR TITLE
add /etc/profile loading to /etc/zsh/zprofile

### PR DESCRIPTION
**Pull request by thomasbeaudry**
solves #64 i think.  It adds the /etc/profile to the zprofile.  @joshunrau do you want to test this?  I can run this play on your machine.  let me know.

### CODE REVIEW

**Comment by joshunrau** [comment]
How do I test? I will be remote tmr because of some car maintenance. Can I test over SSH or does it have to be in-person?

**Comment by thomasbeaudry** [comment]
@joshunrau yes you can test this remotely with ssh, but actually after looking at your system, this PR change has already been made to it (I guess by gabriel).  If it's working properly right now, then maybe there is nothing to test.  @gdevenyi what do you think?

**Comment by gdevenyi** [comment]
Yes, I already manually fixed dnpws15

**Comment by thomasbeaudry** [comment]
@gdevenyi well if your  fix just did what this PR did (and nothing else), then it's ready to be merged

**Pull request merged**
